### ISSUE TITLE
XML Parser Error

### ISSUE THREAD

**Issue by fesch89** [NETWAYS/check_all3000#1]
If I try to run the plugin on an ALLNET ALL3419 I get the following XML Parser Error:

> [root@icinga2 myplugins]# ./check_allnet.pl -H 10.8.1.98 -U icinga -P icinga -u 104 -w 35 -c 38
> Entity: line 1: parser error : EntityRef: expecting ';'
> t-weight: bold;">XML Help<br /><br /></pre><pre>http://10.8.1.98/xml?mode=*&type
>                                                                                 ^
> Entity: line 1: parser error : EntityRef: expecting ';'
> ht: bold;">XML Help<br /><br /></pre><pre>http://10.8.1.98/xml?mode=*&type=**&id
>                                                                                 ^
> Entity: line 1: parser error : EntityRef: expecting ';'
> XML Help<br /><br /></pre><pre>http://10.8.1.98/xml?mode=*&type=**&id=***&action
>                                                                                 ^
> Entity: line 1: parser error : Opening and ending tag mismatch: pre line 1 and body
>   ***id: actor/sensor ID (optional)<br />****action: 0/1 (optional)<br /></body>
>                                                                                 ^
> Entity: line 1: parser error : Premature end of data in tag html line 1
> d: actor/sensor ID (optional)<br />****action: 0/1 (optional)<br /></body><html>
>                                                                                 ^
> Entity: line 1: parser error : Premature end of data in tag body line 1
> d: actor/sensor ID (optional)<br />****action: 0/1 (optional)<br /></body><html>
>                                                                                 ^
> Entity: line 1: parser error : Premature end of data in tag head line 1
> d: actor/sensor ID (optional)<br />****action: 0/1 (optional)<br /></body><html>
>                                                                                 ^
> Entity: line 1: parser error : Premature end of data in tag head line 1
> d: actor/sensor ID (optional)<br />****action: 0/1 (optional)<br /></body><html>
>                                                                                 ^
> Entity: line 1: parser error : Premature end of data in tag html line 1
> d: actor/sensor ID (optional)<br />****action: 0/1 (optional)<br /></body><html>
>                                                                                ^

**Comment by martialblog** [comment]
Hi, 

Sorry the delay. I just pushed some updates to this branch: https://github.com/NETWAYS/check_all3000/tree/fix/xml-issues

If it's still relevant feel free to test it. Worked with Perl v5.36.0

**Comment by martialblog** [comment]
Should work with https://github.com/NETWAYS/check_all3000/pull/3 merged
