### ISSUE TITLE
XML Parse error with ALL3419 on Ubu 18.04

### ISSUE THREAD

**Issue by blindzero** [NETWAYS/check_all3000#2]
Hi,

I just tried the plugin with our ALL3419 on Ubu18.04.
Direct XML HTTP request is working:
`
   <sensor>
      <id>1</id>
      <name>Intern</name>
      <current>28.56</current>
      <unit>°C</unit>
      <minmax>
            <today>
                  <min>
                        <value>28.18</value>
                        <date>20.05.2020 00:00:07</date>
                        <timestamp>1589925607</timestamp>
                  </min>
                  <max>
                        <value>30.09</value>
                        <date>20.05.2020 12:55:51</date>
                        <timestamp>1589972151</timestamp>
                  </max>
            </today>
            <absolute>
                  <min>
                        <value>18.75</value>
                        <date>13.06.2017 14:14:14</date>
                        <timestamp>1497356054</timestamp>
                  </min>
                  <max>
                        <value>40.36</value>
                        <date>16.03.2017 09:09:40</date>
                        <timestamp>1489651780</timestamp>
                  </max>
            </absolute>
      </minmax>
</sensor>
`

Checking by plugin always gives a parsing error, no matter which -u port I am requesting:

`
root@icinga2:/usr/lib/nagios/plugins# ./check_all3000.pl -H 1.2.3.4 -u 1 -w 30 -c 40 -U username -P 'mypassword'

not well-formed (invalid token) at line 1, column 243, byte 243 at /usr/lib/x86_64-linux-gnu/perl5/5.26/XML/Parser.pm line 187.
XML::Simple called at ./check_all3000.pl line 191.
`

It doesn't seem to be an authentication issue as I really get a 401 authentication error when changing the password to something false.

Best,
Matthias

**Comment by blindzero** [comment]
Hi,
is that not maintained anymore?
Best,
Matthias

**Comment by martialblog** [comment]
Hi, 

Sorry the delay. I just pushed some updates to this branch: https://github.com/NETWAYS/check_all3000/tree/fix/xml-issues

If it's still relevant feel free to test it. Worked with Perl v5.36.0

**Comment by martialblog** [comment]
Should work with https://github.com/NETWAYS/check_all3000/pull/3 merged
